spring:
  profiles: pro
  datasource:
    username: root
    password: 123456sw
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dingemployee?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9090

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: AUTO