spring:
  profiles: pro
  datasource:
    username: root
    password: 123456sw
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nas?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8
logging:
  file:
    path: classpath:log/logging.log
    name: logging.log
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: AUTO
NAS:
  api: http://9jfjbs.natappfree.cc/cgi-bin/
  username: admin
  password: 123456sw
