spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 123456sw
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000   
    #mybatis-plus 
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true    

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义token过期时间  单位（分钟）
token:
  expireTime: 10

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: info
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#  ssl:
#    key-store:  classpath:\tomcat.keystore
#    key-store-password: 123456
#    keyStoreType: JKS
#    keyAlias: tomcat

  
  